apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        env:
        - name: MAX_HEAP
          value: "800m"
        - name: MIN_HEAP
          value: "300m"
        resources:
          limits:
            memory: "20Gi"
            cpu: "2000m"
          requests:
            memory: "6Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /sonatype-work
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc