apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: build
spec:
  selector:
    app: nexus-server
  ports:
  - name: nexus-port
    port: 8081
    targetPort: 8081
  - name: docker-on-nexus-port
    port: 8085
    targetPort: 8085
  - name: docker-nexus-https
    port: 8086
    targetPort: 8086
  type: LoadBalancer