apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: build
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"


    
